### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by wangzl2011** [GitLqr/LQRAudioRecord#5]
java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	at java.io.File.fixSlashes(File.java:183)
	at java.io.File.<init>(File.java:130)

这个问题怎么解决啊 ， 7.0手机

**Comment by lzou** [comment]
你这报错截的有点短啊 ，是不是没有读写sd卡权限啊
